### ISSUE TITLE
Docker Image with REST API?

### ISSUE THREAD

**Issue by Slyke** [rhasspy/piper#410]
Hello, I can see that this project is the successor to [Mycroft's Mimic3](https://github.com/MycroftAI/mimic3?tab=readme-ov-file#web-server). I was wondering if there's a docker container for this project so that something like this can be achieved:

```
curl -X POST --data 'Hello world.' --output - localhost:59125/api/tts | aplay
```

At the moment, I have Mimic3 running on my Kubernetes cluster, and use it for a bunch of things, but it has some issues with parsing SSML, and it looks like the project is abandoned and the main developer has moved here.

I have integrated Mimic3 on my cluster into Home Assistant:
```
tts:
  - platform: marytts
    host: 10.25.29.113
    port: 59125
    codec: "WAVE_FILE"
    language: "en_US"
    voice: "en_US/hifi-tts_low#92"
  - platform: google_translate
```

But would rather it be separate from Home Assistant and instead be managed by Kubernetes since it has high availability (several nodes and i7 CPUs) as apposed to a single RPi4. I didn't see anything on the main readme about running an API server in Python
