### ISSUE TITLE
Kubernetes Deployment inside

### ISSUE THREAD

**Issue by Links2004** [rhasspy/piper#69]
not sure where the best place is to put this, 
but here is a Kubernetes Deployment for piper.

I use it with my Home Assistant running in Kubernetes.

Happy to make a PR if i know where to add it.
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  labels:
    app: piper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: piper
  template:
    metadata:
      labels:
        app: piper
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: piper
      containers:
        - name: piper
          image: rhasspy/wyoming-piper:latest
          #imagePullPolicy: IfNotPresent
          args:
            - --voice
            - en-us-libritts-high
          env:
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 10200
              protocol: TCP
              name: piper
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            limits:
              cpu: 12000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: piper
spec:
  selector:
    app: piper
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 10200
      targetPort: 10200
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: piper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 384Mi
  volumeMode: Filesystem
```
