### ISSUE TITLE
Cannot access Cori voice via Docker.  Please fix like Add-on!

### ISSUE THREAD

**Issue by bwims** [rhasspy/piper#762]
Hello,

The fix implemented by https://github.com/home-assistant/addons/pull/3688 has not been implemented for the Docker version.

I still cannot access the Cori voice via Docker.

Thanks!

**Comment by bwims** [comment]
Any thoughts?

**Comment by bwims** [comment]
Bump!  I realise this is best dealt with in wyoming-piper, but it doesn't seem that anyone is looking at issues there!

**Comment by AndreKR** [comment]
Just in case you are not aware, the workaround is:
* [Download](https://github.com/rhasspy/piper/blob/master/VOICES.md) cori (model and config) and put it in your data directory
* In `en_GB-cori-medium.onnx.json` change `"dataset": "cori"` to `"dataset": "en_GB-cori-medium"`.
* Restart Piper

**Comment by bwims** [comment]
Thanks.  In the end, I got help from ChatGPT and edited the voices.json file to include a section for cori, including size and MD5 .

It now seems to work with HA voice assistant, even though it still has the dataset field as "training".  Interestingly, the dataset field for  en_GB-alan-medium.onnx.json set to "alan", not "en_GB-alan-medium" , so the format doesn't seem essential.

Wouldn't it be nice if 
(a)  all this hacking were properly documented
(b) someone would fix the Docker file
(c) someone looked at the issues from time to time

It's not that I'm ungrateful, just frustrated!

Thanks again.

**Comment by bwims** [comment]
Good tip!

**Comment by bwims** [comment]
Hmm.  It looks like home assistant does need voices.json edited to work with the esphome voice hardware at least.

FYI Here's how I made it work:

Portainer stack (docker-compose)

```
version: '3'
services:
  piper:
    container_name: Piper
    environment:
        - TZ=Europe/London
    image: rhasspy/wyoming-piper:1.5.0
    restart: unless-stopped
    ports:
      - 10200:10200
    volumes:
      - '/home/piper:/data'
      - '/home/piper/voices.json:/usr/local/lib/python3.9/dist-packages/wyoming_piper/voices.json'      
      - '/etc/localtime:/etc/localtime'
    network_mode: host

```

Downloaded en_GB-cori-medium.onnx, en_GB-cori-medium.onnx.json into /home/piper:/data

Put the following section into voices.json

```
"en_GB-cori-medium": {
  "key": "en_GB-cori-medium",
  "name": "cori",
  "language": {
    "code": "en_GB",
    "family": "en",
    "region": "GB",
    "name_native": "English",
    "name_english": "English",
    "country_english": "Great Britain"
  },
  "quality": "medium",
  "num_speakers": 1,
  "speaker_id_map": {},
  "files": {
    "en_GB-cori-medium.onnx": {
      "size_bytes": YOUR_SIZE,
      "md5_digest": "YOUR_MD5"
    },
    "en_GB-cori-medium.onnx.json": {
      "size_bytes": YOUR_SIZE,
      "md5_digest": "YOUR_MD5"
    }
  },
  "aliases": []
}

```

Ran the following commands to get the values for YOUR_SIZE and YOUR_MD5 for the two files:

```
md5sum en_GB-cori-medium.onnx
md5sum en_GB-cori-medium.onnx.json

stat --format="%s" en_GB-cori-medium.onnx
stat --format="%s" en_GB-cori-medium.onnx.json

```

Restarted piper, reloaded piper in HA and the voice was available to home assistant voices.

Seems to work ok.

Maybe someone could forward this to the docker/piper maintainer?
